server:
    port: 9001
    tomcat:
        connection-timeout: 2s
        keep-alive-timeout: 15s
        threads:
            max: 50
            min-spare: 5
    shutdown: graceful
polar:
    greeting: Welcome to the local book catalog!

spring:
    application:
        name: catalog-service
    lifecycle:
        timeout-per-shutdown-phase: 15s
    config:
        import: ""
    cloud:
        config:
            enabled: false
            uri: http://localhost:8888
            request-connect-timeout: 5000
            request-read-timeout: 5000
            fail-fast: false
            retry:
                max-attempts: 30
                initial-interval: 1000
                max-interval: 2000
                multiplier: 1.1
    datasource:
        username: user
        password: password
        url: jdbc:postgresql://localhost:5432/polardb_catalog
        hikari:
            connection-timeout: 2000
            maximum-pool-size: 5
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/PolarBookshop
management:
    endpoints:
        web:
            exposure:
                include: refresh, health, prometheus
    endpoint:
        health:
            show-details: always
            show-components: always
            probes:
                enabled: true
    metrics:
        tags:
            application: ${spring.application.name}
logging:
  pattern:
      level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"