apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - deployment.yaml
    - service.yaml

configMapGenerator:
    -   name: catalog-config
        namespace: polar
        files:
            - application.yaml
        options:
            labels:
                app: catalog-service